<div class="">
    <div class="w-full p-2">
        <h5>Report Name : {{$result->report_name}}</h5>
        <h5>Start Periode : {{$result->start_date}}</h5>
        <h5>End Periode : {{$result->end_date}}</h5>
        <h5>Generated By : {{$result->registered->name}}</h5>
        <h5>Generated At : {{$result->created_at}}</h5>
    </div>
    <div class="tableDataWrapper" style="min-height:700px;">
        <table class="tableData">
            <thead>
                <tr>
                    <th rowspan=2><span>Rank</span></th>
                    <th rowspan=2><span>Sales Name</span></th>
                    <th colspan=3>Sales</th>
                    <th colspan=3>New Customer</th>
                    <th colspan=3>Interaction</th>
                    <th colspan=3>Conversion</th>
                    <th rowspan=2>Final Score</th>
                </tr>
                <tr>
                    <th>Actual</th>
                    <th>Target</th>
                    <th>Score</th>
                    <th>Actual</th>
                    <th>Target</th>
                    <th>Score</th>
                    <th>Actual</th>
                    <th>Target</th>
                    <th>Score</th>
                    <th>Prospect</th>
                    <th>Rate</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                @php 
                    $i = 0; 
                    $temp_score = -1; 
                @endphp
                @foreach($results as $row)
                @php 
                    if($row->final_score == $temp_score){}
                    else{$i++;}
                @endphp

                    <tr>
                        <td class="sm:bg-yellow-300">{{$i}}</td>
                        <td class="sm:bg-yellow-300">{{$row->user->name}}</td>
                        <td>{{number_format($row->sales_actual,2, ',', '.')}}</td>
                        <td>{{number_format($row->sales_target,2, ',', '.')}}</td>
                        <td>{{number_format($row->sales_score,3, ',', '.')}}</td>

                        <td>{{number_format($row->customer_actual,2, ',', '.')}}</td>
                        <td>{{number_format($row->customer_target,2, ',', '.')}}</td>
                        <td>{{number_format($row->customer_score,3, ',', '.')}}</td>


                        <td>{{number_format($row->interaction_actual,2, ',', '.')}}</td>
                        <td>{{number_format($row->interaction_target,2, ',', '.')}}</td>
                        <td>{{number_format($row->interaction_score,3, ',', '.')}}</td>


                        <td>{{number_format($row->prospect_actual,2, ',', '.')}}</td>
                        <td>{{number_format($row->conversion_rate,2, ',', '.')}}</td>
                        <td>{{number_format($row->conversion_score,3, ',', '.')}}</td>

                        <td>{{number_format($row->final_score,5, ',', '.')}}</td>
                    </tr>
                @php 
                    $temp_score = $row->final_score; 
                @endphp
                @endforeach
            </tbody>
        </table>
    </div>
</div>
